### ISSUE TITLE
http: panic serving 127.0.0.1:57464: interface conversion: interface {} is nil, not string

### ISSUE THREAD

**Issue by jmalghem** [la5nta/pat#225]
Hello,

I'm having an issue trying to connect to a remote station.
My installation is Yaesu FT-847 driven by rigctld (rigctl(d), Hamlib 3.3) using serial port
Pat version is : Pat v0.10.0 (601f6d3) linux/amd64 - go1.15.1
OS is Ubuntu : 20.04
Winmor Sound Card TNC : 1.5.12.0 on wine 5.0

When I try to connect to a remote station, as soon as the remote station reply, I got a go exception. My station seems to ack "2 cars..." multiple time and finally failed to establish the connection.
The pat connect log is bellow :

_2020/10/22 04:15:54 Connecting to HB9PC (winmor)...
2020/10/22 04:16:08 QSX winmor: 3602.500
2020/10/22 04:16:08 http: panic serving 127.0.0.1:57464: interface conversion: interface {} is nil, not string
goroutine 124 [running]:
net/http.(*conn).serve.func1(0xc0002d2000)
	/usr/local/go/src/net/http/server.go:1801 +0x147
panic(0x934620, 0xc000286660)
	/usr/local/go/src/runtime/panic.go:975 +0x3e9
github.com/la5nta/wl2k-go/transport/winmor.(*TNC).getString(...)
	/media/Diverse/Development/Go/pkg/mod/github.com/la5nta/wl2k-go@v0.7.2/transport/winmor/tnc.go:463
github.com/la5nta/wl2k-go/transport/winmor.(*TNC).MyCall(0xc000242900, 0x3, 0xc000268640, 0x11, 0xa78360)
	/media/Diverse/Development/Go/pkg/mod/github.com/la5nta/wl2k-go@v0.7.2/transport/winmor/tnc.go:306 +0xab
github.com/la5nta/wl2k-go/transport/winmor.(*TNC).Dial(0xc000242900, 0xc0001ee01f, 0x5, 0x1, 0x0, 0x14, 0xc65bd95a6c)
	/media/Diverse/Development/Go/pkg/mod/github.com/la5nta/wl2k-go@v0.7.2/transport/winmor/dial.go:118 +0xd7
github.com/la5nta/wl2k-go/transport/winmor.(*TNC).DialURL(0xc000242900, 0xc00020a420, 0xc0001ee015, 0x6, 0xc0000c0538, 0x1)
	/media/Diverse/Development/Go/pkg/mod/github.com/la5nta/wl2k-go@v0.7.2/transport/winmor/dial.go:103 +0x1d2
github.com/la5nta/wl2k-go/transport.DialURL(0xc00020a420, 0x18, 0xc0003518d8, 0x2, 0x2)
	/media/Diverse/Development/Go/pkg/mod/github.com/la5nta/wl2k-go@v0.7.2/transport/dial.go:29 +0xb2
main.Connect(0xc0001ee015, 0x1b, 0x0)
	/home/martinhpedersen/github/la5nta/pat/connect.go:143 +0x3ae
main.ConnectHandler(0xa72820, 0xc0006e01c0, 0xc000274b00)
	/home/martinhpedersen/github/la5nta/pat/http.go:462 +0x9b
net/http.HandlerFunc.ServeHTTP(0x9f3b40, 0xa72820, 0xc0006e01c0, 0xc000274b00)
	/usr/local/go/src/net/http/server.go:2042 +0x44
github.com/gorilla/mux.(*Router).ServeHTTP(0xc000194770, 0xa72820, 0xc0006e01c0, 0xc000274900)
	/media/Diverse/Development/Go/pkg/mod/github.com/gorilla/mux@v1.6.1/mux.go:159 +0x106
net/http.(*ServeMux).ServeHTTP(0xf9b6c0, 0xa72820, 0xc0006e01c0, 0xc000274900)
	/usr/local/go/src/net/http/server.go:2417 +0x1ad
net/http.serverHandler.ServeHTTP(0xc0001e2000, 0xa72820, 0xc0006e01c0, 0xc000274900)
	/usr/local/go/src/net/http/server.go:2843 +0xa3
net/http.(*conn).serve(0xc0002d2000, 0xa73b20, 0xc0002d0000)
	/usr/local/go/src/net/http/server.go:1925 +0x8ad
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2969 +0x36c
2020/10/22 04:16:08 QSY winmor: 3602.5
2020/10/22 04:16:12 Connecting to HB9PC (winmor)...
2020/10/22 04:16:12 Unable to establish connection to remote: A connect is in progress.
2020/10/22 04:16:13 QSX winmor: 3602.500_

Any help will be appreciated!

Thanks and best 73s,
F4GVY

**Comment by martinhpedersen** [comment]
@jmalghem Are you still having this issue? Winmor is deprecated in favor of ardop, but we could consider digging in to this if it's still an issue.

Log output when executed with the env variable WINMOR_DEBUG=1 would be of great help.

Thanks!

**Comment by martinhpedersen** [comment]
Closing this, as winmor is not longer supported.
